zy/47 fix multiline issue
anusii/rdflib pull request #48
Opened 2024-07-29 16:03 UTC by zheyxu

Handle with test file:

`@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix show: <http://example.org/vocab/show/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

show:218 rdfs:label "That Seventies Show"^^xsd:string .            
show:218 rdfs:label "That Seventies Show"^^<http://www.w3.org/2001/XMLSchema#string> . 
show:218 rdfs:label "That Seventies Show" .                                           
show:218 show:localName "That Seventies Show"@en .                 
show:218 show:localName 'Cette Série des Années Soixante-dix'@fr . 
show:218 show:localName "Cette Série des Années Septante"@fr-be .  
show:218 show:blurb '''This is a multi-line
literal with many quotes (""""")
and up to two sequential apostrophes ('').'''^^xsd:string .`

And in parse result, `(""""")` is convert to ([\, "][\, "][\, "][\, "][\, "]) to avoid parse exception (petitparser seems to only accent one pair of `"` in one literal).

2024-07-30 05:41 UTC, anushkavidanage requested changes
This does not seem to work in my testing? example_7.dart file does not parse the turtle content as expected. Am I doing something wrong here?

2024-07-30 05:46 UTC, zheyxu commented
> This does not seem to work in my testing? example_7.dart file does not parse the turtle content as expected. Am I doing something wrong here?

Can you parse the result?

2024-08-01 23:54 UTC, anushkavidanage approved these changes

2024-08-01 23:55 UTC, anushkavidanage commented
All works well on Windows. It would be good if we can test this on Linux as well

2024-08-02 00:05 UTC, zheyxu commented
> All works well on Windows. It would be good if we can test this on Linux as well

Thanks @anushkavidanage, it has been tested on Linux and works well.

2024-08-05 10:46 UTC, srodriguez142857 commented
@zheyxu 
I have the following two observations:

1) 
![image](https://github.com/user-attachments/assets/12c666fe-6743-492d-8666-30da436289c3)

2) 
![image](https://github.com/user-attachments/assets/557880f4-d6a0-45a3-9306-25523ecfc5b7)

2024-08-06 00:52 UTC, zheyxu commented
Hi @srodriguez142857, made updates accordingly

<img width="1098" alt="Screenshot 2024-08-06 at 10 52 03 AM" src="https://github.com/user-attachments/assets/4c851329-31d6-4f2e-8873-f656f9584f8e">

2024-08-06 03:53 UTC, srodriguez142857 commented
Hi @zheyxu.

The output looks compliant with the Turtle spec: [Quoted Literals section](https://www.w3.org/TR/turtle/#turtle-literals).

It would be ideal to have a thorough check of the syntax production rule for the [`[17] String`](https://www.w3.org/TR/turtle/#grammar-production-String).
However, as for now, the update is complete and serves our purposes.

All good.

2024-08-06 03:55 UTC, srodriguez142857 approved these changes

2024-08-06 04:07 UTC, merged